module.exports = {
  apps: [
    {
      name: "lms-api",
      script: "app.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_memory_restart: "700M",
      env: {
        NODE_ENV: "production",
        PROCESS_ROLE: "api",
        PORT: 5000,
        HOST: "127.0.0.1",
        MAX_CONCURRENT_EXECUTIONS: 2,
        MAX_PENDING_EXECUTIONS: 100,
        EXECUTION_QUEUE_TIMEOUT_MS: 30000,
        EXECUTION_TMP_DIR: "/var/tmp",
      },
    },
    {
      name: "lms-execution",
      script: "app.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_memory_restart: "1500M",
      env: {
        NODE_ENV: "production",
        PROCESS_ROLE: "execution",
        PORT: 5005,
        HOST: "127.0.0.1",
        CODE_EXECUTION_MODE: "docker",
        ALLOW_UNSAFE_LOCAL_EXECUTION: "false",
        MAX_CONCURRENT_EXECUTIONS: 12,
        MAX_PENDING_EXECUTIONS: 1000,
        EXECUTION_QUEUE_TIMEOUT_MS: 60000,
        EXECUTION_TIMEOUT_MS: 5000,
        EXECUTION_COMPILE_TIMEOUT_MS: 30000,
        EXECUTION_TMP_DIR: "/var/tmp",
      },
    },
  ],
};
